# Generated by Django 3.2.6 on 2021-10-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211003_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_last_name',
            new_name='last_name',
        ),
    ]
