# Generated by Django 3.2.6 on 2021-09-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_bag',
            field=models.TextField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='strtipe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
