# Generated by Django 3.2.6 on 2021-09-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210903_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='allergens',
        ),
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.ManyToManyField(blank=True, null=True, related_name='allergen_list', to='products.Allergens'),
        ),
    ]
