# Generated by Django 3.2.6 on 2021-09-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210903_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='allergens',
        ),
        migrations.AddField(
            model_name='product',
            name='allergen',
            field=models.ManyToManyField(to='products.Allergens'),
        ),
    ]
