# Generated by Django 3.2.6 on 2021-09-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_allergen_product_allergens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='allergens',
        ),
    ]
