# Generated by Django 3.2.6 on 2021-09-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_allergens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allergens',
            new_name='Allergen',
        ),
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.ManyToManyField(to='products.Allergen'),
        ),
    ]
