# Generated by Django 3.2.6 on 2021-09-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210904_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='allergens',
            field=models.ManyToManyField(blank=True, to='products.Allergen'),
        ),
    ]
