# Generated by Django 3.2.6 on 2021-09-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210912_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_meal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
    ]
