# Generated by Django 3.2.6 on 2021-09-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210915_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_topping_large',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='price_topping_medium',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
