# Generated by Django 3.2.6 on 2021-09-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210915_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_three_sizes',
            field=models.BooleanField(default=False),
        ),
    ]
