# Generated by Django 3.2.6 on 2021-09-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_has_three_sizes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_three_sizes',
            new_name='has_sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='size_large',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='size_medium',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
