# Generated by Django 3.2.6 on 2021-10-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20211013_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='small', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_large',
            field=models.CharField(default='large', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_medium',
            field=models.CharField(default='medium', max_length=10),
        ),
    ]
