# Generated by Django 3.2.6 on 2021-10-15 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20211015_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_toppings',
        ),
    ]
